str = "RajaRamMohanRoy"
print(str)
print(len(str))
print(str[2:5])
print(str[-2:-5])
print(str[2:8:2])
print(str[-3:-7:-1])
print(str[5:-6])
print(str[-8:-4])
print(str[::])
print(str[::3])
print(str[::-1])
print(str[-3:-11:-2])
print(str[2:8:0])